services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      MONGO_URI: ${MONGO_URI}
    ports:
      - '3333:3333'
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

volumes:
  mongo_data:
